export const BUILTIN_FONTS = [
  { name: 'Caveat',               family: 'Caveat',               category: 'casual'  },
  { name: 'Indie Flower',         family: 'Indie Flower',         category: 'casual'  },
  { name: 'Kalam',                family: 'Kalam',                category: 'casual'  },
  { name: 'Patrick Hand',         family: 'Patrick Hand',         category: 'casual'  },
  { name: 'Architects Daughter',  family: 'Architects Daughter',  category: 'casual'  },
  { name: 'Coming Soon',          family: 'Coming Soon',          category: 'casual'  },
  { name: 'Just Another Hand',    family: 'Just Another Hand',    category: 'casual'  },
  { name: 'Reenie Beanie',        family: 'Reenie Beanie',        category: 'casual'  },
  { name: 'Bad Script',           family: 'Bad Script',           category: 'casual'  },
  { name: 'Nanum Pen Script',     family: 'Nanum Pen Script',     category: 'casual'  },
  { name: 'Loved by the King',    family: 'Loved by the King',    category: 'casual'  },
  { name: 'Gochi Hand',           family: 'Gochi Hand',           category: 'casual'  },
  { name: 'Sriracha',             family: 'Sriracha',             category: 'casual'  },
  { name: 'Handlee',              family: 'Handlee',              category: 'casual'  },
  { name: 'Schoolbell',           family: 'Schoolbell',           category: 'casual'  },
  { name: 'Dawning of a New Day', family: 'Dawning of a New Day', category: 'casual'  },
  { name: 'Sue Ellen Francisco',  family: 'Sue Ellen Francisco',  category: 'casual'  },
  { name: 'Zeyada',               family: 'Zeyada',               category: 'casual'  },
  { name: 'Cedarville Cursive',   family: 'Cedarville Cursive',   category: 'casual'  },
  { name: 'Kristi',               family: 'Kristi',               category: 'casual'  },
  { name: 'Dancing Script',       family: 'Dancing Script',       category: 'cursive' },
  { name: 'Sacramento',           family: 'Sacramento',           category: 'cursive' },
  { name: 'Shadows Into Light',   family: 'Shadows Into Light',   category: 'cursive' },
  { name: 'Homemade Apple',       family: 'Homemade Apple',       category: 'cursive' },
  { name: 'Great Vibes',          family: 'Great Vibes',          category: 'cursive' },
  { name: 'Pacifico',             family: 'Pacifico',             category: 'cursive' },
  { name: 'Satisfy',              family: 'Satisfy',              category: 'cursive' },
  { name: 'Cookie',               family: 'Cookie',               category: 'cursive' },
  { name: 'Allura',               family: 'Allura',               category: 'cursive' },
  { name: 'Alex Brush',           family: 'Alex Brush',           category: 'cursive' },
  { name: 'Parisienne',           family: 'Parisienne',           category: 'cursive' },
  { name: 'Marck Script',         family: 'Marck Script',         category: 'cursive' },
  { name: 'Meddon',               family: 'Meddon',               category: 'cursive' },
  { name: 'Qwigley',              family: 'Qwigley',              category: 'cursive' },
  { name: 'Rouge Script',         family: 'Rouge Script',         category: 'cursive' },
  { name: 'Permanent Marker',     family: 'Permanent Marker',     category: 'bold'    },
  { name: 'Rock Salt',            family: 'Rock Salt',            category: 'bold'    },
  { name: 'Gloria Hallelujah',    family: 'Gloria Hallelujah',    category: 'bold'    },
  { name: 'Covered By Your Grace',family: 'Covered By Your Grace',category: 'bold'    },
  { name: 'Amatic SC',            family: 'Amatic SC',            category: 'bold'    },
  { name: 'Patrick Hand SC',      family: 'Patrick Hand SC',      category: 'bold'    },
  { name: 'Mrs Saint Delafield',  family: 'Mrs Saint Delafield',  category: 'elegant' },
  { name: 'Pinyon Script',        family: 'Pinyon Script',        category: 'elegant' },
  { name: 'Tangerine',            family: 'Tangerine',            category: 'elegant' },
  { name: 'Euphoria Script',      family: 'Euphoria Script',      category: 'elegant' },
  { name: 'Licorice',             family: 'Licorice',             category: 'elegant' },
  { name: 'Petit Formal Script',  family: 'Petit Formal Script',  category: 'elegant' },
  { name: 'Shadows Into Light Two',family:'Shadows Into Light Two',category: 'elegant'},
  { name: 'Give You Glory',       family: 'Give You Glory',       category: 'elegant' },
  { name: 'Waiting for the Sunrise',family:'Waiting for the Sunrise',category:'elegant'},
];
export const FONT_CATEGORIES = ['all', 'casual', 'cursive', 'bold', 'elegant', 'local', 'custom'];
